version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    restart: always
    container_name: dg01
    command: gunicorn config.wsgi --bind 0.0.0.0:80
    depends_on:
      - db
    volumes:
      - /static:/static
    expose:
      - "80"
  db:
    image: postgres:latest
    restart: always
    container_name: ps01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bentel
