version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    hostname: db
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: admin
      POSTGRES_DB: bentel
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./boot.sh
    volumes:
      - .:/bentel
    ports:
      - "8000:8000"
    links:
      - postgres