version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    hostname: db
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: admin
      POSTGRES_DB: bentel
  web:
    image: bentel
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bentel
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - migration
  migration:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bentel
    command: ["python", "manage.py", "migrate", "api"] 
    volumes:
      - .:/bentel
    links:
      - postgres
    depends_on:
      - postgres