version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    depends_on:
      - db
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: ps01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bentel
