# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=60)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('codigoPais', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursos', to='api.Cocinero')),
                ('inscritos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.Alumno')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='alumno',
            index_together=set([('nombre', 'codigoPostal', 'codigoPais')]),
        ),
    ]
