# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 11:11
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=60)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('codigoPais', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='cocinero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursos', to='api.Cocinero'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(to='api.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together=set([('nombre', 'codigoPostal', 'codigoPais')]),
        ),
        migrations.AlterIndexTogether(
            name='alumno',
            index_together=set([('nombre', 'codigoPostal', 'codigoPais')]),
        ),
    ]
