# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='inscritos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='api.Curso'),
        ),
    ]
