# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170825_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cursos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(to='api.Curso'),
        ),
    ]
